core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path('secret :) /', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('posts/', include('posts.urls', namespace='posts')),
] 
# + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)  

posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

urlpatterns = [
    path('<int:year>/<int:month>/<int:day>/<int:post_id>/', views.post_detail, name='post_detail') ,
    path('profile/<int:user_id>', views.user_dashboard, name='dashboard' ) ,
    path('category/<int:cat_id>', views.post_categories, name='post_categories' ) ,
    path('add-post/', views.add_post, name='add_post') ,
    path('delete-post/<int:user_id>/<int:post_id>', views.delete_post, name='delete_post') ,
    path('edit-post/<int:user_id>/<int:post_id>', views.edit_post, name='edit_post') ,
    path('add-reply/<int:post_id>/<int:comment_id>', views.add_reply, name='add_reply') ,
    path('', views.all_posts, name='all_posts') ,
]

posts/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse


class Category(models.Model):
    '''
    Category class model in blog app

    name field is not primaryKey.
    '''
    name =     models.CharField(max_length=50)

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('posts:post_categories', args=[self.id])


class Post(models.Model):
    '''
    The Post Model Class

    User and Category are ForeignKey
    '''
    user =      models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='posts')
    category =  models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True, related_name='cposts')
    body =      models.TextField(max_length=500)
    created =   models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} - {self.body[:30]}'

    def get_absolute_url(self):
        return reverse('posts:post_detail', args=[self.created.year, self.created.month, self.created.day, self.id])


class Comment(models.Model):
    user =      models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='ucomments')
    post =      models.ForeignKey(Post, on_delete=models.CASCADE, related_name='pcomments')
    reply =     models.ForeignKey('self', on_delete=models.CASCADE, related_name='rcomments', null=True, blank=True)
    is_reply =  models.BooleanField(default=False)
    body =      models.TextField(max_length=400)
    created =   models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.user.full_name} - {self.body[:20]}'
    

posts/forms.py
from django import forms
from django.forms import widgets
from .models import Post, Comment

 
class AddPostForm(forms.ModelForm):
    class Meta :
        model = Post
        fields = ('body','category',)

        widgets = {
            'body':forms.Textarea(attrs={
                'class' :'form-control' ,
            }),
            'category':forms.Select(attrs={
                'class' :'form-control' ,
            }),
        }
        
        error_messages = {
            'body': {
                'required': 'این فیلد اجباری است'
            }
        }



class EditPostForm(forms.ModelForm):
    class Meta :
        model = Post
        fields = ('body','category',)

        widgets = {
            'body':forms.Textarea(attrs={
                'class' :'form-control' ,
            }),
            'category':forms.Select(attrs={
                'class' :'form-control' ,
            }),
        }
        
        error_messages = {
            'body': {
                'required': 'این فیلد اجباری است'
            }
        }



class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        widgets = {
            'body':forms.Textarea(attrs={
                'class' :'form-control' ,
                'rows' : "3"
            }),
        }
        labels = {
            'body' : '',
        }
        error_messages = {
            'body': {
                'required': 'این فیلد اجباری است'
            }
        }



class AddReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        widgets = {
            'body':forms.Textarea(attrs={
                'class' :'form-control' ,
            }),
        }
        

posts/views.py
from django.shortcuts import get_object_or_404, render , redirect
from django.contrib.auth.decorators import login_required
from accounts.models import User
from .models import Category ,Post, Comment
from .forms import AddPostForm, EditPostForm, AddCommentForm, AddReplyForm
from django.contrib import messages


def all_posts(request):
    ''' post list function

        the list of records is without any filter
    '''
    posts = Post.objects.all()
    categories = Category.objects.all()
    context = {
        'posts': posts ,
        'categories': categories,
    }
    return render(request, 'posts/all_posts.html', context)



def post_detail(request, year, month, day, post_id):
    post = get_object_or_404(Post, created__year=year, created__month=month, created__day=day, id=post_id) 
    comments = Comment.objects.filter(post=post, is_reply=False)
    categories = Category.objects.all()
    reply_form = AddReplyForm()
    if request.method == 'POST':
        form = AddCommentForm(request.POST)
        if form.is_valid():
            cm = form.save(commit=False)
            cm.post = post
            cm.user = request.user
            cm.save()
            messages.success(request, 'نظر شما با موفقیت ثبت شد', 'success')
    form = AddCommentForm()
    context = {
        'post': post ,
        'comments': comments ,
        'form' : form,
        'reply_form': reply_form ,
        'categories': categories,
    }
    return render(request, 'posts/post_detail.html', context)



#@login_required
def user_dashboard(request, user_id):
    user = get_object_or_404(User, id = user_id)
    posts = Post.objects.filter(user = user)
    categories = Category.objects.all()
    context = {
        'user': user ,
        'posts': posts ,
        'categories': categories,
    }
    return render(request, 'posts/dashboard.html', context)


@login_required
def add_post(request):
    categories = Category.objects.all()
    if request.method == 'POST':
        form = AddPostForm(request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.user = request.user
            new_post.save()
            messages.success(request, 'با موفقیت منتشر شد', 'success')
            return redirect('posts:dashboard', request.user.id)
    else :
        form = AddPostForm()
    context = {
        'form': form ,
        'categories': categories,
    }
    return render(request, 'posts/add_post.html', context)


@login_required
def delete_post(request, user_id ,post_id):
    if user_id == request.user.id :
        the_post = Post.objects.filter(id=post_id)
        the_post.delete()
        messages.success(request, 'با موفقیت حذف شد', 'success')
        return redirect('posts:dashboard', request.user.id)
    else :
        return redirect('posts:all_posts')


@login_required
def edit_post(request, user_id, post_id):
    categories = Category.objects.all()
    if user_id == request.user.id :
        the_post = get_object_or_404(Post, id=post_id)
        if request.method == 'POST':
            form = EditPostForm(request.POST, instance=the_post)
            if form.is_valid():
                form.save()
                messages.success(request, 'با موفقیت ویرایش شد', 'success')
                return redirect('posts:dashboard', request.user.id)
        else:
            form = EditPostForm(instance=the_post)
        context = {
            'form': form ,
            'categories': categories,
        }
        return render(request, 'posts/edit_post.html', context)
    else :
        return redirect('posts:all_posts')


@login_required
def add_reply(request, post_id, comment_id):
    the_post = get_object_or_404(Post, id = post_id)
    the_comment = get_object_or_404(Comment, id = comment_id)
    if request.method == 'POST':
        form = AddReplyForm(request.POST)
        if form.is_valid():
            rp = form.save(commit=False)
            rp.post = the_post
            rp.user = request.user
            rp.reply = the_comment
            rp.is_reply = True
            rp.save()
            messages.success(request, 'نظر شما با موفقیت ثبت شد', 'success')
    return redirect('posts:post_detail', the_post.created.year, the_post.created.month, the_post.created.day, the_post.id)


def post_categories(request, cat_id):
    the_category = get_object_or_404(Category, id=cat_id)
    posts = Post.objects.filter(category=the_category)
    categories = Category.objects.all()
    context = {
        'posts':posts ,
        'categories': categories ,
        'the_category': the_category,
    }
    return render(request,'posts/post_categories.html',context)

templates/posts/add_post.html
{% extends 'base_social.html' %}
{% block title %} مطلب جدید {% endblock %}
{% block content %}
    <form  action=''  method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <input type='submit' value='ارسال' class='btn btn-primary' >
    </form>
{% endblock %}  

templates/posts/all_posts.html
{% extends 'base_social.html' %}
{% load thumbnail %}
{% block title %} همه نوشته ها {% endblock %}
{% block content %}

  
<!-- Section-->
{% for post in posts %}
<div class="col mb-5">
    <div class="card h-100">
        <!-- Product details-->
        <div class="card-body p-4">
            <div class="text-right" dir='rtl'>
                {% thumbnail post.user.image "300x300" as img %}
                <img class="card-img-top rounded-circle w-25" src="{{ img.url }}" alt="{{ img.name }}" />
                {% endthumbnail %}
                <!-- Product name-->
                <h7 class="fw-bolder"><a style='text-decoration: none; color:#1aa3ff;' href='{% url "posts:dashboard" post.user.id  %}' >{{ post.user.full_name }}</a></h7>
                <!-- Product price-->
                <div class='text-muted'>{{ post.created|date:'H:i / Y-m-d'}}</div>
                <div class='text-left' dir='ltr'><a class='btn btn-warning' href='{{ post.category.get_absolute_url }}'>{{ post.category }}</a></div>
                <a style='text-decoration: none; color:#444444;' href='{{ post.get_absolute_url }}' >{{ post.body }}</a>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %} 

templates/posts/dashboard.html
{% extends 'base_social.html' %}
{% load thumbnail %}
{% block title %} پروفایل - {{ user.full_name }}  {% endblock %}
{% block content %}

<!-- Section-->
{% for post in posts %}
<div class="col mb-5">
    <div class="card h-100">
        <!-- Product details-->
        <div class="card-body p-4">
            <div class="text-right" dir='rtl'>
                {% thumbnail post.user.image "300x300" as img %}
                <img class="card-img-top rounded-circle w-25" src="{{ img.url }}" alt="{{ img.name }}" />
                {% endthumbnail %}
                <!-- Product name-->
                <h7 class="fw-bolder"><a style='text-decoration: none; color:#1aa3ff;' href='{% url "posts:dashboard" post.user.id  %}' >{{ post.user.full_name }}</a></h7>
                <!-- Product price-->
                <div class='text-muted'>{{ post.created|date:'H:i / Y-m-d'}}</div>
                <div class='text-left' dir='ltr'><a class='btn btn-warning' href='{{ post.category.get_absolute_url }}'>{{ post.category }}</a></div>
                <a style='text-decoration: none; color:#444444;' href='{{ post.get_absolute_url }}' >{{ post.body }}</a>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %} 

templates/posts/edit_post.html
{% extends 'base_social.html' %}
{% block title %} ویرایش مطلب {% endblock %}
{% block content %}
    <form  action=''  method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <input type='submit' value='ثبت ویرایش' class='btn btn-primary' >
        <a href="{% url 'posts:all_posts' %}" type="button" class="btn btn-danger">انصراف</a>
    </form>
{% endblock %} 
 

templates/posts/post_categories.html
{% extends 'base_social.html' %}
{% load thumbnail %}
{% block title %} {{ the_category.name }} {% endblock %}
{% block content %}

  
<!-- Section-->
{% for post in posts %}
<div class="col mb-5">
    <div class="card h-100">
        <!-- Product details-->
        <div class="card-body p-4">
            <div class="text-right" dir='rtl'>
                {% thumbnail post.user.image "300x300" as img %}
                <img class="card-img-top rounded-circle w-25" src="{{ img.url }}" alt="{{ img.name }}" />
                {% endthumbnail %}
                <!-- Product name-->
                <h7 class="fw-bolder"><a style='text-decoration: none; color:#1aa3ff;' href='{% url "posts:dashboard" post.user.id  %}' >{{ post.user.full_name }}</a></h7>
                <!-- Product price-->
                <div class='text-muted'>{{ post.created|date:'H:i / Y-m-d'}}</div>
                <div class='text-left' dir='ltr'><a class='btn btn-warning' href='{{ post.category.get_absolute_url }}'>{{ post.category }}</a></div>
                <a style='text-decoration: none; color:#444444;' href='{{ post.get_absolute_url }}' >{{ post.body }}</a>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %} 

templates/posts/post_detail.html
{% extends 'base_detail_post.html' %}
{% load thumbnail %}
{% block title %} {{ post.user.full_name }} {% endblock %}
{% block content %}

<!--#########################################################-->
        <!-- Page content-->
        <div class="container mt-5">
            <div class="row">
                <div class="col-20">
                    <!-- Post content-->
                    <article>
                        <!-- Post header-->
                        <header class="mb-4">
                            {% thumbnail post.user.image "300x300" as img %}
                               <img class="card-img-top rounded-circle w-25" style='max-height: 120px; max-width: 120px;' src="{{ img.url }}" alt="{{ img.name }}" />
                            {% endthumbnail %}
                            <!-- Post meta content-->
                            <div class="text-muted  mb-2">
                                <h7 class="fw-bolder"><a style='text-decoration: none; color:#1aa3ff;' href='{% url "posts:dashboard" post.user.id  %}' >{{ post.user.full_name }}</a></h7>
                            </div>
                            <div class="text-muted  mb-2">
                                <div class='text-muted'>{{ post.created|date:'H:i / Y-m-d'}}</div>
                            </div>
                            <!-- Post categories-->
                            <div class='text-left' dir='rtl'><a class='btn btn-warning' href='{{ post.category.get_absolute_url }}'>{{ post.category }}</a></div>
                        </header>
                        {% if request.user.id == post.user.id %}
                            <p >
                                <a class='text-danger' href='{% url "posts:delete_post" post.user.id  post.id  %}' > حذف پست</a> | 
                                <a class='text-danger' href='{% url "posts:edit_post" post.user.id  post.id  %}' > ویرایش پست</a>
                            </p>
                        {% endif %}
                        <!-- Post content-->
                        <section class="mb-5">
                            <p class="fs-5 mb-4">{{ post.body }}</p>
                        </section>
                        <div>تعداد دیدگاه ها: {{ comments.count }} </div>
                    </article>


                    <!-- Comments section-->
                    <section class="mb-5">
                        <div class="card bg-light">
                            <div class="card-body">
                                <!-- Comment form-->
                                {% if request.user.is_authenticated %}
                                    <form  class='mb-4' action='' method=POST>
                                        {% csrf_token %}
                                        {{ form.as_p }}
                                        <input type='submit' value='ارسال دیدگاه' class='btn btn-primary'>
                                    </form>
                                {% else %}
                                    <p>برای ارسال دیدگاه باید وارد سیستم شوید</p>
                                {% endif %}
                                <!-- Comment with nested comments-->
                                
                                    {% for comment in comments %}
                                    <div class="d-flex mb-4">
                                        <!-- Parent comment-->
                                        {% thumbnail comment.user.image "300x300" as img %}
                                            <div class="flex-shrink-0"><img class="rounded-circle" style='max-height: 60px; max-width: 60px;' src="{{ img.url }}" alt="{{ img.name }}" /></div>
                                        {% endthumbnail %}
                                        <div class="ms-3">
                                            <div class="fw-bold">{{ comment.user.full_name }}</div>
                                            {{ comment.body }}
                                        </div>
                                    </div>
                                    {% empty %}
                                        <div class="ms-3" >دیدگاهی نوشته نشده است</div>
                                    {% endfor %}
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>
{% endblock %} 